name: setup

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show env
        run: |
          cat /etc/os-release
          echo $AWS_DEFAULT_REGION
          echo ${{github.ref_name}}

      - name: Terraform init
        run: |
          make init
      
      - name: Terraform plan
        run: |
          make plan
      
      - name: Terraform apply
        run: |
          make apply

      - name: Terraform output
        run: |
          make output